### ISSUE TITLE
Game runs worse

### ISSUE THREAD

**Issue by DestructiveBurn** [fkortsagin/The-Blair-Witch-Project-Volume-1-Rustin-Parr-Windows-10-Fix#1]
Not sure what you're fix does, but doors don't open and the flashlight flickers.   In the menu there is no Vodoo 3dfx card just my GTX 1080 that pops up.  Also, there is no FHD at all.

I was hoping this would've fixed the cut scene issue when she gets to the hotel without turning off Hardware Mode or how she floats above the couch when she sits.   I'll stick to the original.  At least the doors open when you press the switch and the flashlight doesn't flicker.

**Comment by silentgameplays** [comment]
She always flows above the couch during that cutscene,even with the original without the dgvoodoo fix. Original should run fine without the dgvoodoo fix with just 98/ME compatibility,run as admin and the resolution fix,also when installing the game turn off Geforce Experience and some other green processes,because they interfere with the 32bit setup for all three games.

**Comment by DestructiveBurn** [comment]
I figured it out, your video helped out.  Good to know it's a normal issue with the couch in the office.

I am on Day 4 with the old woman.    The settings work well.  Besides the random crashes at the town.  I tried to get it to work in Window mode but unfortunately it won't.

I'll most likely be making a full tutorial on my website on how to set it up with your video, links and other things like a walkthrough and cheats.  But right now, busy having fun. :)

dgvoodoo sure made it way better.  Thanks again!

**Comment by silentgameplays** [comment]
Thank you for the amazing feedback and support! Currently noticing that a lot of older games run much better under Linux with the exception of Silent Hill 3. But these Blair Witch/Nocturne game series are amazing,much better than the latest Blair Witch (2019) from Bloober Team game,too bad the developers abandoned them. :)
